// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV4vv9vehNfm9Qm1Q0jNSq1BQvJBLshjI',
    appId: '1:411917406242:web:a4ce12c18ae8231dc77a7b',
    messagingSenderId: '411917406242',
    projectId: 'kecap-pintar',
    authDomain: 'kecap-pintar.firebaseapp.com',
    storageBucket: 'kecap-pintar.firebasestorage.app',
    measurementId: 'G-L9B15KTS2E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPYJfj1lw6udwCGvaFGOl5Di6tQaHJ4Qo',
    appId: '1:411917406242:android:2fc565cff454d64dc77a7b',
    messagingSenderId: '411917406242',
    projectId: 'kecap-pintar',
    storageBucket: 'kecap-pintar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpw1ZR1-kAcZQDZsJX1JJ50RkqbPb8yXs',
    appId: '1:411917406242:ios:15550d3e17ae7d89c77a7b',
    messagingSenderId: '411917406242',
    projectId: 'kecap-pintar',
    storageBucket: 'kecap-pintar.firebasestorage.app',
    iosClientId: '411917406242-c6no74fg8qo7nf4p7133n35jf9s7c18f.apps.googleusercontent.com',
    iosBundleId: 'com.example.kecap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpw1ZR1-kAcZQDZsJX1JJ50RkqbPb8yXs',
    appId: '1:411917406242:ios:15550d3e17ae7d89c77a7b',
    messagingSenderId: '411917406242',
    projectId: 'kecap-pintar',
    storageBucket: 'kecap-pintar.firebasestorage.app',
    iosClientId: '411917406242-c6no74fg8qo7nf4p7133n35jf9s7c18f.apps.googleusercontent.com',
    iosBundleId: 'com.example.kecap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDV4vv9vehNfm9Qm1Q0jNSq1BQvJBLshjI',
    appId: '1:411917406242:web:6067cc83cb14cc44c77a7b',
    messagingSenderId: '411917406242',
    projectId: 'kecap-pintar',
    authDomain: 'kecap-pintar.firebaseapp.com',
    storageBucket: 'kecap-pintar.firebasestorage.app',
    measurementId: 'G-2XQNN5EHYD',
  );
}
